---
title: Gosod lleoliad corluniau gyda haenau
hero_image: images/banner.png
description: Galli di osod lleoliad corluniau fel eu bod yn ymddangos o flaen neu y tu ôl i gorluniau eraill
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Gosod lleoliad corluniau gyda haenau
