---
title: Figuren mit Ebenen positionieren
hero_image: images/banner.png
description: Du kannst Figuren so positionieren, dass sie vor oder hinter anderen Figuren erscheinen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Figuren mit Ebenen positionieren
