---
title: Posicione atores utilizando camadas
hero_image: images/banner.png
description: Você pode posicionar atores de forma que eles apareçam na frente ou atrás de outros atores
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Posicione atores utilizando camadas
