---
title: Posicionar objetos en capas
hero_image: images/banner.png
description: Puedes colocar objetos para que aparezcan delante o detrás de otros objetos
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Posicionar objetos en capas
