---
title: Ustaw duszki na warstwach
hero_image: images/banner.png
description: Możesz ustawić duszki tak, aby pojawiały się przed lub za innymi duszkami
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Ustaw duszki na warstwach
