---
title: Placera sprajter med lager
hero_image: images/banner.png
description: Du kan placera sprajter så att de visas framför eller bakom andra sprajter
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Placera sprajter med lager
