---
title: Position sprites with layers
hero_image: images/banner.png
description: You can position sprites so that they appear in front of or behind other sprites
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Position sprites with layers
