---
title: Positionner les sprites avec des couches
hero_image: images/banner.png
description: Tu peux positionner les sprites de manière à ce qu'ils apparaissent devant ou derrière d'autres sprites
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Positionner les sprites avec des couches
