---
title: Posiziona gli sprite sui livelli dello Stage
hero_image: images/banner.png
description: Puoi posizionare gli sprite in modo che appaiano davanti o dietro altri sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Posiziona gli sprite sui livelli dello Stage
